# Build settings
remote_theme: pages-themes/tactile@v0.2.0
plugins:
- jekyll-remote-theme
gem "github-pages", group: :jekyll_plugins
title: [Diego Trazzi]
description: [A short description of computer science things]